name: Deploy to GitHub Pages

on:
  push:
    branches:
      - goto 

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 依存関係をインストール（yarn）
        run: yarn install

      - name: ビルド（yarn build）
        run: yarn build

      - name: GitHub Pages にデプロイ
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
