name: Deploy to GitHub Pages

on:
  push:
    branches:
      - goto 

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Git の author 情報を設定
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: 依存関係をインストール（yarn）
        run: yarn install

      - name: ビルド（yarn build）
        run: yarn build

      - name: GitHub Pages にデプロイ（直実行）
        run: |
          npx gh-pages -d build \
            -u "github-actions[bot] <github-actions[bot]@users.noreply.github.com>" \
            --repo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/OneKiloWatt/aerumap.git"
